server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lemon?serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

pebble:
  cache: false
  suffix: .html